import TanstackProvider from '@/providers/tanstackProvider';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import JotaiProvider from '@/providers/jotaiProvider';

const inter = Inter({ subsets: ['latin'] });

const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<Providers>
					<div>{children}</div>
				</Providers>
			</body>
		</html>
	);
}

function Providers({ children }: { children: React.ReactNode }) {
	return (
		<TanstackProvider>
			<JotaiProvider>{children}</JotaiProvider>
		</TanstackProvider>
	);
}
